//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z21Client.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Z21Client.Resources.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to AllLocoInfoReceived event. Adding AllLocoInfo broadcast flag..
        /// </summary>
        internal static string Text0001 {
            get {
                return ResourceManager.GetString("Text0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribing from AllLocoInfoReceived event. Removing AllLocoInfo broadcast flag..
        /// </summary>
        internal static string Text0002 {
            get {
                return ResourceManager.GetString("Text0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to RailComDataReceived event. Adding AllRailCom broadcast flag and starting polling..
        /// </summary>
        internal static string Text0003 {
            get {
                return ResourceManager.GetString("Text0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribing from RailComDataReceived event. Removing AllRailCom broadcast flag and stopping polling..
        /// </summary>
        internal static string Text0004 {
            get {
                return ResourceManager.GetString("Text0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to RBusDataReceived event. Adding RBus broadcast flag..
        /// </summary>
        internal static string Text0005 {
            get {
                return ResourceManager.GetString("Text0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribing from RBusDataReceived event. Removing RBus broadcast flag..
        /// </summary>
        internal static string Text0006 {
            get {
                return ResourceManager.GetString("Text0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing to SystemStateChanged event. Adding SystemState broadcast flag..
        /// </summary>
        internal static string Text0007 {
            get {
                return ResourceManager.GetString("Text0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribing from SystemStateChanged event. Removing SystemState broadcast flag..
        /// </summary>
        internal static string Text0008 {
            get {
                return ResourceManager.GetString("Text0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Z21 at {Host}:{Port}....
        /// </summary>
        internal static string Text0009 {
            get {
                return ResourceManager.GetString("Text0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected. Please disconnect first..
        /// </summary>
        internal static string Text0010 {
            get {
                return ResourceManager.GetString("Text0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: Host {Host} is not reachable (ping failed)..
        /// </summary>
        internal static string Text0011 {
            get {
                return ResourceManager.GetString("Text0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address provided: {Host}.
        /// </summary>
        internal static string Text0012 {
            get {
                return ResourceManager.GetString("Text0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UdpClient created and bound to listen on local port {Port}.
        /// </summary>
        internal static string Text0013 {
            get {
                return ResourceManager.GetString("Text0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create and bind UdpClient on port {Port}. The port may already be in use by another application..
        /// </summary>
        internal static string Text0014 {
            get {
                return ResourceManager.GetString("Text0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: Host responded to ping, but did not respond to Z21 command (handshake failed)..
        /// </summary>
        internal static string Text0015 {
            get {
                return ResourceManager.GetString("Text0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z21 client connection verified and fully started..
        /// </summary>
        internal static string Text0016 {
            get {
                return ResourceManager.GetString("Text0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnecting from Z21....
        /// </summary>
        internal static string Text0017 {
            get {
                return ResourceManager.GetString("Text0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive task was successfully cancelled as expected during disconnect..
        /// </summary>
        internal static string Text0018 {
            get {
                return ResourceManager.GetString("Text0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive task did not cancel within the expected time during disconnect..
        /// </summary>
        internal static string Text0019 {
            get {
                return ResourceManager.GetString("Text0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected..
        /// </summary>
        internal static string Text0020 {
            get {
                return ResourceManager.GetString("Text0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLocoInfoAsync: Requested loco info for address {Address}.
        /// </summary>
        internal static string Text0021 {
            get {
                return ResourceManager.GetString("Text0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLocoModeAsync: Requested loco mode for address {Address}.
        /// </summary>
        internal static string Text0022 {
            get {
                return ResourceManager.GetString("Text0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRailComDataAsync: Requested RailCom info for loco {locoAddress}.
        /// </summary>
        internal static string Text0023 {
            get {
                return ResourceManager.GetString("Text0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRBusDataAsync: Requested R-Bus data for group index {groupIndex}.
        /// </summary>
        internal static string Text0024 {
            get {
                return ResourceManager.GetString("Text0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSerialtNumberAsync: Requested z21/Z21 serial number.
        /// </summary>
        internal static string Text0025 {
            get {
                return ResourceManager.GetString("Text0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSystemStateAsync: Requested system state.
        /// </summary>
        internal static string Text0026 {
            get {
                return ResourceManager.GetString("Text0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTurnoutModeAsync: Requested turnout mode for address {address}.
        /// </summary>
        internal static string Text0027 {
            get {
                return ResourceManager.GetString("Text0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetZ21CodeAsync: Requested z21/Z21 (feature) code.
        /// </summary>
        internal static string Text0028 {
            get {
                return ResourceManager.GetString("Text0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set loco drive for address {Address}: Speed={Speed}, rocoValue={rocoValue} NativeSteps={NativeSpeedSteps}, Direction={Direction}.
        /// </summary>
        internal static string Text0029 {
            get {
                return ResourceManager.GetString("Text0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle function {functionIndex} for loco address {address}.
        /// </summary>
        internal static string Text0030 {
            get {
                return ResourceManager.GetString("Text0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting loco mode for address {Address} to {Mode}.
        /// </summary>
        internal static string Text0031 {
            get {
                return ResourceManager.GetString("Text0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Emergency Stop command..
        /// </summary>
        internal static string Text0032 {
            get {
                return ResourceManager.GetString("Text0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting turnout mode for address {Address} to {Mode}.
        /// </summary>
        internal static string Text0033 {
            get {
                return ResourceManager.GetString("Text0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting turnout position address {address}, position {position}.
        /// </summary>
        internal static string Text0034 {
            get {
                return ResourceManager.GetString("Text0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting track power off.
        /// </summary>
        internal static string Text0035 {
            get {
                return ResourceManager.GetString("Text0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting track power on.
        /// </summary>
        internal static string Text0036 {
            get {
                return ResourceManager.GetString("Text0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred during ping to {Host}..
        /// </summary>
        internal static string Text0037 {
            get {
                return ResourceManager.GetString("Text0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending keep-alive message to Z21..
        /// </summary>
        internal static string Text0038 {
            get {
                return ResourceManager.GetString("Text0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting RailCom data from next locomotive in ring buffer.
        /// </summary>
        internal static string Text0039 {
            get {
                return ResourceManager.GetString("Text0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Z21 lost. No response to multiple pings..
        /// </summary>
        internal static string Text0040 {
            get {
                return ResourceManager.GetString("Text0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No message received from Z21 for a while. Pinging to check connection....
        /// </summary>
        internal static string Text0041 {
            get {
                return ResourceManager.GetString("Text0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping successful, Z21 is still on the network. Waiting for data..
        /// </summary>
        internal static string Text0042 {
            get {
                return ResourceManager.GetString("Text0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping failed. Failure count: {Count}.
        /// </summary>
        internal static string Text0043 {
            get {
                return ResourceManager.GetString("Text0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred during watchdog ping. Failure count: {Count}.
        /// </summary>
        internal static string Text0044 {
            get {
                return ResourceManager.GetString("Text0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send command. Client is not connected..
        /// </summary>
        internal static string Text0045 {
            get {
                return ResourceManager.GetString("Text0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send command to central station. Exception: {message}.
        /// </summary>
        internal static string Text0046 {
            get {
                return ResourceManager.GetString("Text0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the receive loop. Exception: {message}.
        /// </summary>
        internal static string Text0047 {
            get {
                return ResourceManager.GetString("Text0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received malformed data: not enough bytes to read message length. Remaining bytes: {Length}.
        /// </summary>
        internal static string Text0048 {
            get {
                return ResourceManager.GetString("Text0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered zero-length message in data stream. Stopping parse of this packet..
        /// </summary>
        internal static string Text0049 {
            get {
                return ResourceManager.GetString("Text0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received malformed data: buffer is smaller than the indicated message length. Expected: {Expected}, Actual remaining: {Actual}.
        /// </summary>
        internal static string Text0050 {
            get {
                return ResourceManager.GetString("Text0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unhandled or malformed packet. Header: 0x{Header:X4}, Length: {Length}.
        /// </summary>
        internal static string Text0051 {
            get {
                return ResourceManager.GetString("Text0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Loco Slot Info packet is too short. Expected at least 24 bytes, got {Length}.
        /// </summary>
        internal static string Text0052 {
            get {
                return ResourceManager.GetString("Text0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco Slot Info for slot {SlotNumber} received: Address={Address}.
        /// </summary>
        internal static string Text0053 {
            get {
                return ResourceManager.GetString("Text0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an unknown X-Bus command to Z21.
        /// </summary>
        internal static string Text0054 {
            get {
                return ResourceManager.GetString("Text0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received an unhandled X-Bus command with X-Header: 0x{XHeader:X2}.
        /// </summary>
        internal static string Text0055 {
            get {
                return ResourceManager.GetString("Text0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RailCom data for loco {Address} received..
        /// </summary>
        internal static string Text0056 {
            get {
                return ResourceManager.GetString("Text0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z21 Code received: {LockState}.
        /// </summary>
        internal static string Text0057 {
            get {
                return ResourceManager.GetString("Text0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Bus data for group {GroupIndex} received..
        /// </summary>
        internal static string Text0058 {
            get {
                return ResourceManager.GetString("Text0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnout Mode for address {Address} received: {Mode}.
        /// </summary>
        internal static string Text0059 {
            get {
                return ResourceManager.GetString("Text0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Emergency stop packet is too short. Expected 7 bytes, got {Length}.
        /// </summary>
        internal static string Text0060 {
            get {
                return ResourceManager.GetString("Text0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Emergency stop packet with invalid checksum. Received: 0x{Received:X2}, Calculated: 0x{Calculated:X2}. Packet discarded..
        /// </summary>
        internal static string Text0061 {
            get {
                return ResourceManager.GetString("Text0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop received.
        /// </summary>
        internal static string Text0062 {
            get {
                return ResourceManager.GetString("Text0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Turnout Info packet is too short. Expected 9 bytes, got {Length}.
        /// </summary>
        internal static string Text0063 {
            get {
                return ResourceManager.GetString("Text0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Turnout Info packet with invalid checksum. Received: 0x{Received:X2}, Calculated: 0x{Calculated:X2}. Packet discarded..
        /// </summary>
        internal static string Text0064 {
            get {
                return ResourceManager.GetString("Text0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnout Info for address {Address} received: {State}.
        /// </summary>
        internal static string Text0065 {
            get {
                return ResourceManager.GetString("Text0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Track Power Info packet is too short. Expected 7 bytes, got {Length}.
        /// </summary>
        internal static string Text0066 {
            get {
                return ResourceManager.GetString("Text0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Track Power Info packet with invalid checksum. Received: 0x{Received:X2}, Calculated: 0x{Calculated:X2}. Packet discarded..
        /// </summary>
        internal static string Text0067 {
            get {
                return ResourceManager.GetString("Text0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Power State received: {trackPowerInfo}.
        /// </summary>
        internal static string Text0068 {
            get {
                return ResourceManager.GetString("Text0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number received: {SerialNumber}.
        /// </summary>
        internal static string Text0069 {
            get {
                return ResourceManager.GetString("Text0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Info received: {HWType}, Firmware: {FWVersion}.
        /// </summary>
        internal static string Text0070 {
            get {
                return ResourceManager.GetString("Text0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse firmware version from LAN_GET_HWINFO response..
        /// </summary>
        internal static string Text0071 {
            get {
                return ResourceManager.GetString("Text0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware bug workaround: Combined LocoInfo and LocoMode for address {Address} and raised event..
        /// </summary>
        internal static string Text0072 {
            get {
                return ResourceManager.GetString("Text0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco Mode for address {Address} received: {Mode}.
        /// </summary>
        internal static string Text0073 {
            get {
                return ResourceManager.GetString("Text0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast flags received and processed. Flags: 0x{Flags:X8}.
        /// </summary>
        internal static string Text0074 {
            get {
                return ResourceManager.GetString("Text0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Loco Info packet is too short. Expected at least {Length} bytes, got {ActualLength}.
        /// </summary>
        internal static string Text0075 {
            get {
                return ResourceManager.GetString("Text0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Loco Info packet with invalid checksum. Received: 0x{Received:X2}, Calculated: 0x{Calculated:X2}. Packet discarded..
        /// </summary>
        internal static string Text0076 {
            get {
                return ResourceManager.GetString("Text0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware bug workaround: Stored partial LocoInfo for address {Address}, awaiting LocoMode..
        /// </summary>
        internal static string Text0077 {
            get {
                return ResourceManager.GetString("Text0077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco Info for address {Address} received and processed..
        /// </summary>
        internal static string Text0078 {
            get {
                return ResourceManager.GetString("Text0078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware version received and processed: {Version}.
        /// </summary>
        internal static string Text0079 {
            get {
                return ResourceManager.GetString("Text0079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse firmware version from received data..
        /// </summary>
        internal static string Text0080 {
            get {
                return ResourceManager.GetString("Text0080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System state packet is too short. Expected at least 18 bytes, got {Length}.
        /// </summary>
        internal static string Text0081 {
            get {
                return ResourceManager.GetString("Text0081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System state received and successfully processed. Internal voltage: {volt} mV..
        /// </summary>
        internal static string Text0082 {
            get {
                return ResourceManager.GetString("Text0082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting broadcast flags to {subscripedBroadcastFlags}.
        /// </summary>
        internal static string Text0083 {
            get {
                return ResourceManager.GetString("Text0083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetLocoSlotInfoAsync: Requested loco info for slot {slotNumber}.
        /// </summary>
        internal static string Text0084 {
            get {
                return ResourceManager.GetString("Text0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBroadcastFlagsAsync: Requested the broadcast flags.
        /// </summary>
        internal static string Text0085 {
            get {
                return ResourceManager.GetString("Text0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFirmwareVersionAsync: Requested the firmware version.
        /// </summary>
        internal static string Text0086 {
            get {
                return ResourceManager.GetString("Text0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetHardwareInfoAsync: Requested the hardware information.
        /// </summary>
        internal static string Text0087 {
            get {
                return ResourceManager.GetString("Text0087", resourceCulture);
            }
        }
    }
}
